### ISSUE TITLE
Using template literals

### ISSUE THREAD

**Issue by jerricco** [SilbinaryWolf/proposal-fel#4]
Under _Reusable Components_
>`button(class="js-component-button "+kind+" "+width, type=type)`

Apart from the fact we're missing a `"` here. Should read:
```
button(class="js-component-button "+kind+" "+width, type=type)
```

(((N I T P I C K I N G)))

It would be nice to take a page out of JavaScript's book here, mainly because I have a hate for concatenation. Just an awkward syntax to write when dealing with lots of strings (especially in class names). Eg:
```
button(class="js-component-button ${kind}${width}", type=type)
```
Not necessarily the `${}` syntax, but you get the idea. Nice-to-have idea I guess.

**Comment by silbinarywolf** [comment]
I'm actually not a fan of template literals as I feel it hides where a variable is being used a little bit. (When viewing PHP code, I sometimes miss those types of variables.)

I think the best way to manage classes would probably be with an array and then "array.join(" ")" (or whatever I end up calling my version)

Alternatively, I'm more open to a Sprintf function as I find that more readable as an alternate way to concat classes.

**Comment by silbinarywolf** [comment]
As stated previously, this will most likely use array joins for setting the `class` variable neatly.
ie.

```
button(class=["js-component-button",kind, width].join(" "), type=type)
```
or potentially like this as it's nicer for inspecting git history:
```
button(class=[
"js-component-button",
kind, 
width,
].join(" "), type=type)
```

Obviously both will work, but assuming we do a `gofmt`-like thing, It'll probably force the latter (even if I don't personally like the aesthetic)

**Comment by silbinarywolf** [comment]
@jerricco Satisfied to close this?

**Comment by jerricco** [comment]
Yeah, using an array looks cool, though would it make any sense to be able to optionally remove the `.join(" ")` and automatically assume you want each array item as a class spaced by a `&nbsp;`?

Otherwise, yah, happy to have this closed :)

**Comment by silbinarywolf** [comment]
@jerricco I think to begin with, making a user do `.join(" ")` is preferable as it tells them that the value expected by the `class` property is a string-only.

If we want to add that kind of sugar later, it's easy to do, I think I'd just rather that little bit of verboseness as it makes things simpler to understand.

- `class` property only accepts a string (rather than mixed properties)
- Seeing a `.join(" ")` tells you that the variable type is an array when reading the code. Without that, you need to scan upward to see if its a string or array.

The only case where I'd want to allow arrays to "just work" on the `class` property, is if something like Vue.js / Elm / etc allows you to pass an array of values for `class`. From what I can tell with React, you must pass a string for this property.

**Comment by silbinarywolf** [comment]
Applies to old proposal.
